export const PERMISSIONS = {
    MANAGE_WISHES: "MANAGE_WISHES",
    MANAGE_EVENTS: "MANAGE_EVENTS",
    MANAGE_PROJECTS: "MANAGE_PROJECTS",
    MANAGE_TEAMS: "MANAGE_TEAMS",
    MANAGE_SUPPORT: "MANAGE_SUPPORT",
    MANAGE_FEEDBACK: "MANAGE_FEEDBACK",
    MANAGE_MESSAGES: "MANAGE_MESSAGES",
    MANAGE_REPORTS: "MANAGE_REPORTS",
    MANAGE_USERS: "MANAGE_USERS",
    MANAGE_ROLES: "MANAGE_ROLES",
    MANAGE_SETTINGS: "MANAGE_SETTINGS",
    MANAGE_VOLUNTEERS: "MANAGE_VOLUNTEERS"
}

export const PERMISSION_LABELS: Record<string, string> = {
    [PERMISSIONS.MANAGE_WISHES]: "Dilek Yönetimi",
    [PERMISSIONS.MANAGE_EVENTS]: "Etkinlik Yönetimi",
    [PERMISSIONS.MANAGE_PROJECTS]: "Proje Yönetimi",
    [PERMISSIONS.MANAGE_TEAMS]: "Takım Yönetimi",
    [PERMISSIONS.MANAGE_SUPPORT]: "Destek Yönetimi",
    [PERMISSIONS.MANAGE_FEEDBACK]: "Geri Bildirim Yönetimi",
    [PERMISSIONS.MANAGE_MESSAGES]: "Mesaj Yönetimi",
    [PERMISSIONS.MANAGE_REPORTS]: "Rapor Yönetimi",
    [PERMISSIONS.MANAGE_USERS]: "Kullanıcı Yönetimi",
    [PERMISSIONS.MANAGE_ROLES]: "Rol ve Yetki Yönetimi",
    [PERMISSIONS.MANAGE_SETTINGS]: "Ayarlar Yönetimi",
    [PERMISSIONS.MANAGE_VOLUNTEERS]: "Gönüllü Yönetimi"
}

export const DEFAULT_PERMISSIONS: Record<string, string[]> = {
    ADMIN: [
        PERMISSIONS.MANAGE_WISHES,
        PERMISSIONS.MANAGE_EVENTS,
        PERMISSIONS.MANAGE_PROJECTS,
        PERMISSIONS.MANAGE_TEAMS,
        PERMISSIONS.MANAGE_SUPPORT,
        PERMISSIONS.MANAGE_FEEDBACK,
        PERMISSIONS.MANAGE_MESSAGES,
        PERMISSIONS.MANAGE_REPORTS,
        PERMISSIONS.MANAGE_USERS,
        PERMISSIONS.MANAGE_ROLES,
        PERMISSIONS.MANAGE_SETTINGS,
        PERMISSIONS.MANAGE_VOLUNTEERS
    ],
    MEMBER: [
        PERMISSIONS.MANAGE_WISHES,
        PERMISSIONS.MANAGE_EVENTS,
        PERMISSIONS.MANAGE_TEAMS,
        PERMISSIONS.MANAGE_REPORTS
    ],
    USER: []
}

export type Permission = keyof typeof PERMISSIONS
