export const PERMISSIONS = {
    MANAGE_WISHES: "MANAGE_WISHES",
    MANAGE_EVENTS: "MANAGE_EVENTS",
    MANAGE_PROJECTS: "MANAGE_PROJECTS",
    MANAGE_TEAMS: "MANAGE_TEAMS",
    MANAGE_SUPPORT: "MANAGE_SUPPORT",
    MANAGE_FEEDBACK: "MANAGE_FEEDBACK",
    MANAGE_MESSAGES: "MANAGE_MESSAGES",
    MANAGE_REPORTS: "MANAGE_REPORTS",
    MANAGE_USERS: "MANAGE_USERS",
    MANAGE_ROLES: "MANAGE_ROLES",
    MANAGE_SETTINGS: "MANAGE_SETTINGS"
}

export const DEFAULT_PERMISSIONS = {
    ADMIN: [
        PERMISSIONS.MANAGE_WISHES,
        PERMISSIONS.MANAGE_EVENTS,
        PERMISSIONS.MANAGE_PROJECTS,
        PERMISSIONS.MANAGE_TEAMS,
        PERMISSIONS.MANAGE_SUPPORT,
        PERMISSIONS.MANAGE_FEEDBACK,
        PERMISSIONS.MANAGE_MESSAGES,
        PERMISSIONS.MANAGE_REPORTS,
        PERMISSIONS.MANAGE_USERS,
        PERMISSIONS.MANAGE_ROLES,
        PERMISSIONS.MANAGE_SETTINGS
    ],
    MEMBER: [
        PERMISSIONS.MANAGE_WISHES, // Can maybe vote/view?
        PERMISSIONS.MANAGE_EVENTS,
        PERMISSIONS.MANAGE_TEAMS,
        PERMISSIONS.MANAGE_REPORTS
    ],
    USER: []
}
